apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodehello-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nodehello
        track: beta
    spec:
      containers:
        - name: nodehello
          image: "gcr.io/YOURPROJECT/nodehello:v2"
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: 0.2
              memory: "100Mi"

