kind: Service
apiVersion: v1
metadata:
  name: "nodehello-v3"
spec:
  selector:
    app: "nodehello"
    track: "alpha"
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  sessionAffinity: None

