apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodehello-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nodehello
        track: stable
    spec:
      containers:
        - name: nodehello
          image: "gcr.io/kubeweb1/nodehello:v1"
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: 0.2
              memory: "10Mi"

